#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'ohai'
cookbook 'runit'
cookbook 'postgresql', git: 'git://github.com/patientslikeme/chef-postgresql.git'
cookbook 'python'
cookbook 'gunicorn'
cookbook 'supervisor'