#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'openssl'
cookbook 'ohai'
cookbook 'runit'
cookbook 'postgresql', git: 'git://github.com/patientslikeme/chef-postgresql.git'
cookbook 'nginx', git: 'git://github.com/gchef/nginx-cookbook.git', ref: 'v2.7.1'