#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'openssl'
cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'
cookbook 'postgresql', git: 'git://github.com/patientslikeme/chef-postgresql.git'
# cookbook 'rvm',
#   :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'